CREATE DATABASE IF NOT EXISTS Personal_info; 

CREATE TABLE IF NOT EXISTS Passwords (
  ID int(11) AUTO_INCREMENT,
  Service VARCHAR(255),
  Hyperlink VARCHAR(255), 
  Username VARCHAR(255),
  Password VARCHAR(255),
  PRIMARY KEY(ID))
  ENGINE = MyISAM;
